[build]
  command = "npm run build"
  publish = "dist/shop-classy/browser"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 4200
  publish = "dist/shop-classy/browser"
